version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
  build:
    commands:
      - echo "Build started on `date`"
      - pip install -r requirements.txt -t .
      - zip -r lambda.zip *
artifacts:
  files:
    - lambda.zip
post_build:
  commands:
    - echo "Updating lambda Function..."
    - aws lambda update-function-code --function-name data-cloud-project-maps-details --zip-file fileb://deployment_package.zip
    - echo "DONE!!"